import { Book } from './app/shared/models/Book';

export const sample_books: Book[] = [
  {
    id: '1',
    name: 'When the Moon Hatched',
    price: 15,
    favourite: false,
    stars: 4.0,
    Author: 'Sarah A. Parker',
    imageUrl: 'assets/book-1.jpg',
    tags: ['Fantasy', 'Adventure'],
  },
  {
    id: '2',
    name: 'The Full Moon Cat Cafe',
    price: 8,
    favourite: false,
    stars: 3.5,
    Author: 'Mai Mochizuki',
    imageUrl: 'assets/book-2.jpg',
    tags: ['Astrology', 'Motivation'],
  },
  {
    id: '3',
    name: 'Little Red Death',
    price: 11,
    favourite: false,
    stars: 3.0,
    Author: 'Alexandra Benedict',
    imageUrl: 'assets/book-3.jpg',
    tags: ['Fantasy', 'Murder Mystery'],
  },
  {
    id: '4',
    name: 'Astrophysics for People in a hurry',
    price: 12,
    favourite: false,
    stars: 4.0,
    Author: 'Neil Degrasse Tyson',
    imageUrl: 'assets/book-4.jpg',
    tags: ['Science', 'Space'],
  },
  {
    id: '5',
    name: 'Bruce Lee: Fighting Spirit',
    price: 10,
    favourite: false,
    stars: 4.0,
    Author: 'Bruce Thomas',
    imageUrl: 'assets/book-5.jpg',
    tags: ['Biography', 'Lifestyle'],
  },
  {
    id: '6',
    name: 'Murder at the Black Cat Cafe',
    price: 8,
    favourite: false,
    stars: 4.0,
    Author: 'Seishi Yokomizo',
    imageUrl: 'assets/book-6.jpg',
    tags: ['Fantasy', 'Murder Mystery'],
  },
];
